/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CompetitorDTO,
} from '../models';
import {
    CompetitorDTOFromJSON,
    CompetitorDTOToJSON,
} from '../models';

/**
 * 
 */
export class CompetitorControllerApi extends runtime.BaseAPI {

    /**
     */
    async getAllCompetitorsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CompetitorDTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/competitors`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CompetitorDTOFromJSON));
    }

    /**
     */
    async getAllCompetitors(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CompetitorDTO>> {
        const response = await this.getAllCompetitorsRaw(initOverrides);
        return await response.value();
    }

}
