/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GameDTO,
} from '../models';
import {
    GameDTOFromJSON,
    GameDTOToJSON,
} from '../models';

export interface GetAllGamesByRoundIdRequest {
    roundId: number;
}

/**
 * 
 */
export class GameControllerApi extends runtime.BaseAPI {

    /**
     */
    async getAllGamesByRoundIdRaw(requestParameters: GetAllGamesByRoundIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GameDTO>>> {
        if (requestParameters.roundId === null || requestParameters.roundId === undefined) {
            throw new runtime.RequiredError('roundId','Required parameter requestParameters.roundId was null or undefined when calling getAllGamesByRoundId.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/games/round/{roundId}`.replace(`{${"roundId"}}`, encodeURIComponent(String(requestParameters.roundId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GameDTOFromJSON));
    }

    /**
     */
    async getAllGamesByRoundId(requestParameters: GetAllGamesByRoundIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GameDTO>> {
        const response = await this.getAllGamesByRoundIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
