/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RoundDTO,
} from '../models';
import {
    RoundDTOFromJSON,
    RoundDTOToJSON,
} from '../models';

/**
 * 
 */
export class RoundControllerApi extends runtime.BaseAPI {

    /**
     */
    async getAllRoundsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<RoundDTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/rounds`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RoundDTOFromJSON));
    }

    /**
     */
    async getAllRounds(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RoundDTO>> {
        const response = await this.getAllRoundsRaw(initOverrides);
        return await response.value();
    }

}
