/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CommentDTO,
} from '../models';
import {
    CommentDTOFromJSON,
    CommentDTOToJSON,
} from '../models';

export interface GetAllCommentsForRoundRequest {
    roundId: number;
}

/**
 * 
 */
export class RoundCommentControllerApi extends runtime.BaseAPI {

    /**
     */
    async getAllCommentsForRoundRaw(requestParameters: GetAllCommentsForRoundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CommentDTO>>> {
        if (requestParameters.roundId === null || requestParameters.roundId === undefined) {
            throw new runtime.RequiredError('roundId','Required parameter requestParameters.roundId was null or undefined when calling getAllCommentsForRound.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/roundComments/round/{roundId}`.replace(`{${"roundId"}}`, encodeURIComponent(String(requestParameters.roundId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CommentDTOFromJSON));
    }

    /**
     */
    async getAllCommentsForRound(requestParameters: GetAllCommentsForRoundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CommentDTO>> {
        const response = await this.getAllCommentsForRoundRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
