/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompetitorDTO
 */
export interface CompetitorDTO {
    /**
     * 
     * @type {number}
     * @memberof CompetitorDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CompetitorDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CompetitorDTO
     */
    alias?: string;
    /**
     * 
     * @type {number}
     * @memberof CompetitorDTO
     */
    pointsSum?: number;
}

/**
 * Check if a given object implements the CompetitorDTO interface.
 */
export function instanceOfCompetitorDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CompetitorDTOFromJSON(json: any): CompetitorDTO {
    return CompetitorDTOFromJSONTyped(json, false);
}

export function CompetitorDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompetitorDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'alias': !exists(json, 'alias') ? undefined : json['alias'],
        'pointsSum': !exists(json, 'pointsSum') ? undefined : json['pointsSum'],
    };
}

export function CompetitorDTOToJSON(value?: CompetitorDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'alias': value.alias,
        'pointsSum': value.pointsSum,
    };
}

