/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CompetitorDTO } from './CompetitorDTO';
import {
    CompetitorDTOFromJSON,
    CompetitorDTOFromJSONTyped,
    CompetitorDTOToJSON,
} from './CompetitorDTO';

/**
 * 
 * @export
 * @interface GameDTO
 */
export interface GameDTO {
    /**
     * 
     * @type {CompetitorDTO}
     * @memberof GameDTO
     */
    firstCompetitor?: CompetitorDTO;
    /**
     * 
     * @type {CompetitorDTO}
     * @memberof GameDTO
     */
    secondCompetitor?: CompetitorDTO;
    /**
     * 
     * @type {Date}
     * @memberof GameDTO
     */
    scheduledDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof GameDTO
     */
    firstCompetitorScore?: number;
    /**
     * 
     * @type {number}
     * @memberof GameDTO
     */
    secondCompetitorScore?: number;
    /**
     * 
     * @type {number}
     * @memberof GameDTO
     */
    roundOrdinalNumber?: number;
}

/**
 * Check if a given object implements the GameDTO interface.
 */
export function instanceOfGameDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GameDTOFromJSON(json: any): GameDTO {
    return GameDTOFromJSONTyped(json, false);
}

export function GameDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'firstCompetitor': !exists(json, 'firstCompetitor') ? undefined : CompetitorDTOFromJSON(json['firstCompetitor']),
        'secondCompetitor': !exists(json, 'secondCompetitor') ? undefined : CompetitorDTOFromJSON(json['secondCompetitor']),
        'scheduledDate': !exists(json, 'scheduledDate') ? undefined : (new Date(json['scheduledDate'])),
        'firstCompetitorScore': !exists(json, 'firstCompetitorScore') ? undefined : json['firstCompetitorScore'],
        'secondCompetitorScore': !exists(json, 'secondCompetitorScore') ? undefined : json['secondCompetitorScore'],
        'roundOrdinalNumber': !exists(json, 'roundOrdinalNumber') ? undefined : json['roundOrdinalNumber'],
    };
}

export function GameDTOToJSON(value?: GameDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'firstCompetitor': CompetitorDTOToJSON(value.firstCompetitor),
        'secondCompetitor': CompetitorDTOToJSON(value.secondCompetitor),
        'scheduledDate': value.scheduledDate === undefined ? undefined : (value.scheduledDate.toISOString()),
        'firstCompetitorScore': value.firstCompetitorScore,
        'secondCompetitorScore': value.secondCompetitorScore,
        'roundOrdinalNumber': value.roundOrdinalNumber,
    };
}

