/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RoundDTO
 */
export interface RoundDTO {
    /**
     * 
     * @type {number}
     * @memberof RoundDTO
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof RoundDTO
     */
    ordinalNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof RoundDTO
     */
    gamesPlayed?: number;
}

/**
 * Check if a given object implements the RoundDTO interface.
 */
export function instanceOfRoundDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RoundDTOFromJSON(json: any): RoundDTO {
    return RoundDTOFromJSONTyped(json, false);
}

export function RoundDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoundDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'ordinalNumber': !exists(json, 'ordinalNumber') ? undefined : json['ordinalNumber'],
        'gamesPlayed': !exists(json, 'gamesPlayed') ? undefined : json['gamesPlayed'],
    };
}

export function RoundDTOToJSON(value?: RoundDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'ordinalNumber': value.ordinalNumber,
        'gamesPlayed': value.gamesPlayed,
    };
}

